#TODO 보안강화를 위해 .env 파일에 옮기고 github action secret 설정해서 사용(Spring Boot Application에도 코드 추가)
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: PRkVouR_ApYaBb4gie9c
            client-secret: BgKCW4JtK3 #TODO 외부 노출 방지 필요
            redirect-uri: https://feedb.store/login/oauth2/code/naver #고정값(운영일 때 profile에 맞춰 변경)
            authorization-grant-type: authorization_code
            scope: name , email
            client-name: Naver
          kakao:
            client-id: bd9657b9f9347732e4f6bf1eb2e62c4d
            redirect-uri: https://feedb.store/login/oauth2/code/kakao #고정값(운영일 때 profile에 맞춰 변경)
            authorization-grant-type: authorization_code
            scope: profile_nickname , account_email #profile_nickname
            client-name: Kakao
            provider: kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  web:
    resources:
      add-mappings: false
jwt:
  secret: ${JWT_SECRET:default_jwt_secret}

# S3
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:default_access_key}
      secret-key: ${AWS_SECRET_ACCESS_KEY:default_secret_key}
    s3:
      region: ${AWS_REGION:default_region}
    stack:
      auto: false

redirect:
  base-url-local: http://localhost:3000/auth/success
  base-url-prod: https://feedb.vercel.app/auth/success # https://feedb.vercel.app/auth/success


#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE
